# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file desktop/pom.xml

  deploy_release:
      runs-on: ubuntu-latest
      needs: [build_and_test]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v2
          with:
            java-version: 11
            distribution: 'adopt'
        - name: Deploy Release
          run: |
            #mvn -B versions:set -DnewVersion=$GITHUB_SHA -DgenerateBackupPoms=false --file desktop/pom.xml
            mvn -B release:prepare release:perform --file desktop/pom.xml
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
