# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file desktop/pom.xml

  publish-job:
      runs-on: ubuntu-latest
      needs: [build_and_test]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v2
          with:
            java-version: 11
            distibution: 'java-package'
        - name: Publish package
          run: mvn --batch-mode deploy
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        - run: mvn -B package --file desktop/pom.xml -DskipTests
#        - run: mkdir staging && cp desktop/target/*jar-with-dependencies.jar staging
#        - uses: actions/upload-artifact@v2
#          with:
#            name: Package
#            path: staging
